[package]
name = "js-parse"
version = "0.1.0"
authors = ["layton"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
colored = "1.9.3"
regex = "1"
json = "0.12.4"
